# Generated by Django 6.0.5 on 2026-09-29 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_app_rat_user_id_idx_app_rating_user_id_d94130_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AprioriRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('min_support', models.FloatField()),
                ('min_confidence', models.FloatField()),
                ('min_lift', models.FloatField()),
                ('min_rating', models.IntegerField()),
                ('max_len', models.IntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('transactions_count', models.IntegerField(blank=True, null=True)),
                ('rules_count', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssociationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support', models.FloatField()),
                ('confidence', models.FloatField()),
                ('lift', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='app.apriorirun')),
                ('source_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='association_rules_as_source', to='app.book')),
            ],
        ),
        migrations.CreateModel(
            name='AssociationRuleTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='association_rule_targets', to='app.book')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='app.associationrule')),
            ],
        ),
        migrations.DeleteModel(
            name='Recommendation',
        ),
        migrations.AddIndex(
            model_name='associationrule',
            index=models.Index(fields=['confidence'], name='app_associa_confide_4246f0_idx'),
        ),
        migrations.AddIndex(
            model_name='associationrule',
            index=models.Index(fields=['lift'], name='app_associa_lift_61d3af_idx'),
        ),
        migrations.AddIndex(
            model_name='associationrule',
            index=models.Index(fields=['source_book', 'confidence'], name='app_associa_source__7d588e_idx'),
        ),
        migrations.AddConstraint(
            model_name='associationruletarget',
            constraint=models.UniqueConstraint(fields=('rule', 'book'), name='unique_book_per_association_rule'),
        ),
    ]
