# Generated by Django 6.0.5 on 2026-09-29 11:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_apriorirun_associationrule_associationruletarget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apriorirun',
            name='max_len',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2)]),
        ),
        migrations.AlterField(
            model_name='apriorirun',
            name='min_confidence',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='apriorirun',
            name='min_lift',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='apriorirun',
            name='min_rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='apriorirun',
            name='min_support',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='apriorirun',
            name='rules_count',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='apriorirun',
            name='transactions_count',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='associationrule',
            name='confidence',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='associationrule',
            name='lift',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='associationrule',
            name='support',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddConstraint(
            model_name='apriorirun',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='unique_active_apriori_run'),
        ),
        migrations.AddConstraint(
            model_name='apriorirun',
            constraint=models.CheckConstraint(condition=models.Q(('min_support__gte', 0), ('min_support__lte', 1)), name='apriori_support_between_0_and_1'),
        ),
        migrations.AddConstraint(
            model_name='apriorirun',
            constraint=models.CheckConstraint(condition=models.Q(('min_confidence__gte', 0), ('min_confidence__lte', 1)), name='apriori_confidence_between_0_and_1'),
        ),
        migrations.AddConstraint(
            model_name='apriorirun',
            constraint=models.CheckConstraint(condition=models.Q(('min_lift__gte', 0)), name='apriori_lift_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='apriorirun',
            constraint=models.CheckConstraint(condition=models.Q(('min_rating__gte', 1), ('min_rating__lte', 5)), name='apriori_rating_between_1_and_5'),
        ),
        migrations.AddConstraint(
            model_name='apriorirun',
            constraint=models.CheckConstraint(condition=models.Q(('max_len__gte', 2)), name='apriori_max_len_at_least_2'),
        ),
        migrations.AddConstraint(
            model_name='apriorirun',
            constraint=models.CheckConstraint(condition=models.Q(('transactions_count__isnull', True), ('transactions_count__gte', 0), _connector='OR'), name='apriori_transactions_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='apriorirun',
            constraint=models.CheckConstraint(condition=models.Q(('rules_count__isnull', True), ('rules_count__gte', 0), _connector='OR'), name='apriori_rules_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='associationrule',
            constraint=models.CheckConstraint(condition=models.Q(('support__gte', 0), ('support__lte', 1)), name='rule_support_between_0_and_1'),
        ),
        migrations.AddConstraint(
            model_name='associationrule',
            constraint=models.CheckConstraint(condition=models.Q(('confidence__gte', 0), ('confidence__lte', 1)), name='rule_confidence_between_0_and_1'),
        ),
        migrations.AddConstraint(
            model_name='associationrule',
            constraint=models.CheckConstraint(condition=models.Q(('lift__gte', 0)), name='rule_lift_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='rating_between_1_and_5'),
        ),
    ]
